Description: Creates groups, functio and policies for DE

Resources:
  IamRoleDataEngineer:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - sts:AssumeRole
      Description: Function to be enroled by DE
      ManagedPolicyArns:
        - !Ref IamPolicyDataEngineer
      RoleName: role-data-engineer

  IamPolicyDataEngineer:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for DE acess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:List*
              - s3:Get*
              - s3:Delete*
              - s3:Put*
            Resource:
              - arn:aws:s3:::bucket-belisco-turma-5
              - arn:aws:s3:::bucket-belisco-turma-5/*
          - Effect: Allow
            Action:
              - s3:List*
              - s3:Get*
              - s3:Put*
            Resource:
              - arn:aws:s3:::segundo-bucket-belisco-turma-5
              - arn:aws:s3:::segundo-bucket-belisco-turma-5/*

  IamRoleDataScientist:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - sts:AssumeRole
      Description: Function to be assumed by DS
      ManagedPolicyArns:
        - !Ref IamPolicyDataScientist
      RoleName: role-data-scientist

  IamPolicyDataScientist:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for DS acess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:List*
              - s3:Get*
            Resource:
              - arn:aws:s3:::*

  IamGroupDataEngineer:
    Type: AWS::IAM::Group
    Properties:
      GroupName: iam-group-data-engineer
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref IamPolicyGroupDataEngineer

  IamPolicyGroupDataEngineer:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for the DE Group
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !GetAtt IamRoleDataEngineer.Arn

  IamGroupDataScientist:
    Type: AWS::IAM::Group
    Properties:
      GroupName: iam-group-data-scientist
      ManagedPolicyArns:
        - !Ref IamPolicyGroupDataScientist

  IamPolicyGroupDataScientist:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for the DS group
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !GetAtt IamRoleDataScientist.Arn